version: "3.6"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    networks:
      - local-net
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=localpostgres123
      - POSTGRES_USER=admin
      - POSTGRES_DB=coffee
networks:
    local-net:
